language: python
python:
  - "3.6"

services:
  - postgres

env:
  - DJANGO_SETTINGS_MODULE=vacation_management.settings.test

install:
  - export SECRET_KEY="test_key"
  - pip install -r requirements/test.txt
  - psql -c 'create database vacation;' -U postgres
  - python manage.py migrate --noinput

script:
  - pytest
